export { default as Main } from './Main';
export { default as Info } from './Info';
export { default as Testimonials } from './Testimonials';
export { default as Begin } from './Begin';
export { default as Actions } from './Actions';
export { default as Pricing } from './Pricing';
export { default as Calculate } from './Calculate';
export { default as Industry } from './Industry';
export { default as Result } from './Result';
